strictness: high
pyton target: 3
pep8:
  full: true
pylint:
  disable:
    - unused-wildcard-import  # W0614: from X import * --> foo not used
pyflakes:
  disable:
    - F401
doc-warnings: true
test-warnings: true
max-line-length: 100
