language: python
python:
  - '3.6'

install:
  - pip install pygame
  - pip install pypandoc
script: pytest

deploy:
  provider: pypi
  user: ddorn
  password:
    secure: Ye+NumkBHGrDlRHdSFlnnF91PD8dTkW373I/st/Q+mpt5d7EaGuo2AOg60F93uoE09l8HAl0I9ZQ1A7aDWKtfpCDJm1M9m5craILgaU4XrY8b4/PfstqH5sZW1W36KMgauh7M2FW+jb1JwNBBsoCOionE/z/lpt0SVFrjIUkvycogvb5ipnV7MX8ieUKY+dVHDo6HDK5deZOirFtG7HBs4iB8BdU6BvN8IMVDgGx9r+rLirMQ4tvo+30NlvJAGZ40fhTel65VUZkwhcmuZ6cyqGwR07MsxRiiyNvbaxli6xoYKxNTy5DH8teq03qAKb+xzGlQV5XqPoEbcYV3CzqIBQKLgZ/ZumqHcxnloohtcnS8KRxCtEAejMvx/sXv+3PtmU5g2YZtRbN8QRO6v+B6gq8iGDua6D4J4jC/H3t0uAuOXwSdjVPpH70IgKdRlBMdt8Rm5B2xAw5PF+XETgKKtzmB7Szt40uQbB1mEdsTKcOElcZNGp8xoqgRJQWww7nwV+FmQ3UY5mYS/R3XzaMYG+ivHWF0AVrnP1ENeAAQxCSXllH7RsG7XOiVIZs7gY6JqBB5ToxiVFBknatGSnqQIhdzFoPr4w+bd9jPLUbBm7bnN8XVhD5AdIySkMXyga94NcN4RFQS+CjfYv51/41WCnwVFJA5kABcAnxcxHffC8=
  on:
    branch: release
  skip_upload_docs: true # TODO : docs

notifications:
  slack:
    secure: r9rjGrb5ye3LiL7fVwHx3SxHCn4ZSFV3vNzQqiqhQ8vosZ3QTdkKdYl+zk+jJpf0oqwbsBIaHm6AA2bHWDcr7+3R+u0NqHj0rxGrq0w3L4+jBlv5FlOcr+LuikNUvfwiKhqRIO3xNIDxIG+Cc/XF/L+EACFQ+cCS+p8yyi8ScKno/0Kcp19rvuDbxmlJiGfnLHlhPs4RIM5kYRG7SkkR+lmS2PdRM5MqHtJrjcl9a7MxxHqJTzFFA9yl9yk5f7etVhJAErOA9j1loEBeE6NnzczGomwcVsetWNZRAePNCQWBuWpCSc1fHEdUnT1FKvW28LJqnLwKVDdV3a59oR7QF5D0oa9fzZ7CYM57gYOAFImLd+xVXo+j0EujBvN4ngigTTnpCgusF0n2d70Bj7ARGynZtbYVvckRcuCji2NU27EIRWwH/nbmgl4QC739Q8G0s/uL1wsJNyb/DDyVIDhdvBvOXPrybC2M4+BtYTM/qY0oooHywHEfylO7pL12pt93l1EJQb441lHsnHoHoyhc/WFsnRhyldQ9kQNX5Q/ZePmV3JTYEeI/n+14e6S0xW7Br64RuMVuww70TtO/s+xuQjm+2zFEtbwCGWABzxlnmtIZHq1zHViJTt9oUWIoZzfvLSd6MliNjMW48+XKP2EZQA8L8ZBrRpzhYdV4QTPLFbY=
