language: python
python:
  - "3.6"

install:
  - pip install pygame
  - pip install pypandoc

script: pytest

deploy:
  provider: pypi
  user: ddorn
  password:
    secure: YUdgUKRQTgt/AEXfKwn+smVVS+8cW9A8cc1ypOzomwkNKB3gLia6fFdwNEARIygejIA/jnZ8fLZXPBy2zWdJTNIbAVzwT0OvPcrfK4lz/TGD6fZ4gAEwl1P8aw6XBSGR3LMx9SVfZliBgOyRZRyvF+FYkNLpEY1N7Yj3Q11hVCW09rHfVIoYFKNhKWDd1PkAFOgqvMAj3tz6+TCsGC4Hsnp76t/zZ4mLsHtuLPXctFkTjbdn+OJAtFPSAtK0lkOJxAQiNQJ7ko6nlHhLK7t8IjPdLB7BKCunYvgUFUeF/1cdsB8zBEP/DcLCloO91F31FtAGNNYcZsCZvMYLUDefGHccaDuK++U+U4N95DzIKcQ7CQi7YH0paAnRIBsBVcQluuY8a7rRdI2/v+c+OPtz5tu9wa5ZLV1ZDLRhGmEz+Bbqj6M6m1fY1/BWzBrZgm990bIjPEEgyH52VSEza5fAFCzZ3cP7sgZnMwePpaIEw+vwUxcp1qv49R022N+duAruxS67dSWBiJHUerEgSBFBhbYos+WqB/yhYALGHAYqZJ0MGmjDBNpBansG7ysV7E4Arzso22XyVKeH7fQqARxjv+LKJ26OxsvWie0aeKu4uOKYG6YJwb98854B5GfOsvCNY5L8BT2kx0yHw3Ww4maLf42NmbFyQwe7SWJSdSvcHHE=
  on:
    branch: release
